language: node_js
node_js:
- 12.14.1
branchs:
  only:
  - master
addons:
  ssh_known_hosts:
  - 39.108.171.28
before_install:
- openssl aes-256-cbc -K $encrypted_311a3ff6a6ef_key -iv $encrypted_311a3ff6a6ef_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh -P 11111 chenjunxin@39.108.171.28 -o StrictHostKeyChecking=no 'cd /home/chenjunxin/hexoBlogFiles/hexo/ && git pull origin master && npm install && hexo clean && hexo g'